[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["paketo-buildpacks/java", "paketo-buildpacks/maven"]

[env]
JAVA_VERSION = "17"

[start]
cmd = "java -jar target/*.jar"

[build]
builder = "paketobuildpacks/builder:base"
buildCommand = "./mvnw clean package -DskipTests"

[start]
command = "java -jar target/*.jar"
